version: '3.8'

services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "4173:80"  # You can change 4173 to any port you want
    restart: unless-stopped
    environment:
      - NODE_ENV=production